In [2]:
import itertools
import numpy as np
import collections
print(np.__version__)

1.19.2


In [15]:

def matrix_print(metainfo):
    NROWS, NCOLS, m = metainfo[0], metainfo[1], metainfo[2]
    for i in range(NROWS):
        for j in range(NCOLS):
            print(m[i][j], end=' ')
        print('')
        
def matrix_str_print(metainfo):
    NROWS, NCOLS, m = metainfo[0], metainfo[1], metainfo[2]
    for i in range(NROWS):
        for j in range(NCOLS):
            print(m[i*NCOLS+j], end=' ')
        print('')

def canonicalize(NROWS, NCOLS, m):
    possibilities = set()
    for rows in itertools.permutations(range(NROWS)):
        for cols in itertools.permutations(range(NCOLS)):
            p = ''.join(m[r*NCOLS+c] for r in rows for c in cols)
            possibilities.add(p)
#     for p in sorted(possibilities):
#         print(p)
    return [NROWS, NCOLS, min(possibilities)]




############################################################ Ввод матрицы консольно
# print('количество строк:')
# row_count = int(input())
# print('количество столбцов:')
# col_count = int(input())
# print('вводим матрицу:')
# A = []
# for i in range(row_count):
#     A.append(list(map(int, input().split())))
############################################################

############################################################ Задание матрицы
B = [[4, 0, 2, 2, 4, 1],
     [1, 2, 0, 2, 4, 1],
     [3, 2, 1, 2, 4, 1],
     [3, 2, 1, 2, 4, 1],
     [3, 2, 1, 2, 4, 1]]
A = B
row_count = 5
col_count = 6
############################################################

############################################################ Создаем матрицу-строку
string_matrix = ''
for i in range(row_count):
    for j in range(col_count):
        string_matrix += str(A[i][j])
############################################################ 

minm = canonicalize(row_count, col_count, string_matrix)
print('программа выводит:')
# matrix_print([row_count, col_count, A])
matrix_str_print(minm)
print('матрица-строка:', minm[2])


программа выводит:
0 1 1 2 2 4 
1 1 3 2 2 4 
1 1 3 2 2 4 
1 1 3 2 2 4 
2 1 4 0 2 4 
матрица-строка: 011224113224113224113224214024


In [26]:
a = np.array([[6, 1, 6, 1, 1],
              [1, 2, 5, 3, 0],
              [6, 3, 4, 3, 0],
              [6, 4, 3, 3, 0],
              [5, 2, 3, 1, 0],
              [6, 1, 6, 1, 2]])
rows_unordered_cols_ordered_separately = np.sort(a) # ordered columns in each row separately, but no rows
print('rows_unordered_cols_ordered_separately:\n', rows_unordered_cols_ordered_separately)
print(type(rows_unordered_cols_ordered_separately[0,0]))


str_rows_unordered_list = []
for i in range(rows_unordered_cols_ordered_separately.shape[0]):
    str_rows_unordered_list.append(''.join(str(e) for e in rows_unordered_cols_ordered_separately[i]))
print('str_rows_unordered_list', str_rows_unordered_list)

rows_order = np.argsort(str_rows_unordered_list)
rows_ordered = np.empty((0, a.shape[1]), int)

rows_ordered_cols_separately_ordered = np.empty((0, a.shape[1]), int)


for i in rows_order:
    rows_ordered = np.concatenate((rows_ordered, [a[i]]))
    rows_ordered_cols_separately_ordered = np.vstack((rows_ordered_cols_separately_ordered,
                                                           [rows_unordered_cols_ordered_separately[i]]))

print('rows_order:\n', rows_order)
print(type(rows_ordered_cols_separately_ordered[0,0]))
print('rows_ordered_cols_separately_ordered(imaging for group division):\n', rows_ordered_cols_separately_ordered)
print('------------------------------------------------------------------')
print('rows_ordered:\n', rows_ordered)
print(type(rows_ordered[0][0]))
# c = np.sort(b, axis= 0)
# print(c)

rows_unordered_cols_ordered_separately:
 [[1 1 1 6 6]
 [0 1 2 3 5]
 [0 3 3 4 6]
 [0 3 3 4 6]
 [0 1 2 3 5]
 [1 1 2 6 6]]
<class 'numpy.int64'>
str_rows_unordered_list ['11166', '01235', '03346', '03346', '01235', '11266']
rows_order:
 [1 4 2 3 0 5]
<class 'numpy.int64'>
rows_ordered_cols_separately_ordered(imaging for group division):
 [[0 1 2 3 5]
 [0 1 2 3 5]
 [0 3 3 4 6]
 [0 3 3 4 6]
 [1 1 1 6 6]
 [1 1 2 6 6]]
------------------------------------------------------------------
rows_ordered:
 [[1 2 5 3 0]
 [5 2 3 1 0]
 [6 3 4 3 0]
 [6 4 3 3 0]
 [6 1 6 1 1]
 [6 1 6 1 2]]
<class 'numpy.int64'>


In [24]:
groups_tmp = collections.Counter()
print(type(groups_tmp))
rows_group_division = []
for row_index in rows_order:
    groups_tmp[str_rows_unordered_list[row_index]] += 1
    if (groups_tmp[str_rows_unordered_list[row_index]] == 1):
        rows_group_division.append(1)
    else:
        rows_group_division[-1] += 1
print('rows_group_division:\n', rows_group_division)

<class 'collections.Counter'>
rows_group_division:
 [2, 2, 1, 1]


In [40]:
rows_ordered_separately = np.sort(rows_ordered, axis = 0) # ordered columns in each row separately, but no rows
print('rows_ordered_separately:\n', rows_ordered_separately)
str_cols_unordered_list = []
for i in range(rows_ordered_separately.shape[1]):
    str_cols_unordered_list.append(''.join(str(col) for col in rows_ordered_separately[:, i]))

print('str_cols_unordered_list: ', str_cols_unordered_list)

cols_order = np.argsort(str_cols_unordered_list)
print(cols_order)

cols_ordered = np.empty((a.shape[0], 0), int) # it will really cols_ordered_rows_ordered
cols_ordered_rows_separately_ordered = np.empty((a.shape[0], 0), int)
for i in cols_order:
    cols_ordered = np.concatenate((cols_ordered, rows_ordered[:, i:i+1]), axis=1)
    cols_ordered_rows_separately_ordered = np.concatenate((cols_ordered_rows_separately_ordered,
                                                           rows_ordered_separately[:, i:i+1]), axis=1)
print('cols_ordered_rows_separately_ordered(imaging for group division):\n', cols_ordered_rows_separately_ordered)
print('------------------------------------------------------------------')
print('cols_ordered_rows_ordered:\n', cols_ordered)

rows_ordered_separately:
 [[1 1 3 1 0]
 [5 1 3 1 0]
 [6 2 4 1 0]
 [6 2 5 3 0]
 [6 3 6 3 1]
 [6 4 6 3 2]]
str_cols_unordered_list:  ['156666', '112234', '334566', '111333', '000012']
[4 3 1 0 2]
cols_ordered_rows_separately_ordered(imaging for group division):
 [[0 1 1 1 3]
 [0 1 1 5 3]
 [0 1 2 6 4]
 [0 3 2 6 5]
 [1 3 3 6 6]
 [2 3 4 6 6]]
------------------------------------------------------------------
cols_ordered:
 [[0 3 2 1 5]
 [0 1 2 5 3]
 [0 3 3 6 4]
 [0 3 4 6 3]
 [1 1 1 6 6]
 [2 1 1 6 6]]


In [41]:
groups_tmp = collections.Counter()
print(type(groups_tmp))
cols_group_division = []
for col_index in cols_order:
    groups_tmp[str_cols_unordered_list[col_index]] += 1
    if (groups_tmp[str_cols_unordered_list[col_index]] == 1):
        cols_group_division.append(1)
    else:
        cols_group_division[-1] += 1
print('cols_group_division:\n', cols_group_division)

<class 'collections.Counter'>
cols_group_division:
 [1, 1, 1, 1, 1]


In [51]:
group_division = []
max_group_count = max(len(cols_group_division), len(rows_group_division))
for i in range(max_group_count):
    rows_count = cols_count = 0
    if i < len(rows_group_division):
        rows_count = rows_group_division[i]
    if i < len(cols_group_division):
        cols_count = cols_group_division[i]
    group_division.append((rows_count, cols_count))
group_sorted_matrix = cols_ordered
print('group sorted matrix:\n', group_sorted_matrix)
print('group_division: ', group_division)

group sorted matrix:
 [[0 3 2 1 5]
 [0 1 2 5 3]
 [0 3 3 6 4]
 [0 3 4 6 3]
 [1 1 1 6 6]
 [2 1 1 6 6]]
group_division:  [(2, 1), (2, 1), (1, 1), (1, 1), (0, 1)]
