In [113]:
import itertools
import numpy as np
import collections
import copy
print(np.__version__)

1.19.2


In [15]:

def matrix_print(metainfo):
    NROWS, NCOLS, m = metainfo[0], metainfo[1], metainfo[2]
    for i in range(NROWS):
        for j in range(NCOLS):
            print(m[i][j], end=' ')
        print('')
        
def matrix_str_print(metainfo):
    NROWS, NCOLS, m = metainfo[0], metainfo[1], metainfo[2]
    for i in range(NROWS):
        for j in range(NCOLS):
            print(m[i*NCOLS+j], end=' ')
        print('')

def canonicalize(NROWS, NCOLS, m):
    possibilities = set()
    for rows in itertools.permutations(range(NROWS)):
        for cols in itertools.permutations(range(NCOLS)):
            p = ''.join(m[r*NCOLS+c] for r in rows for c in cols)
            possibilities.add(p)
#     for p in sorted(possibilities):
#         print(p)
    return [NROWS, NCOLS, min(possibilities)]




############################################################ Ввод матрицы консольно
# print('количество строк:')
# row_count = int(input())
# print('количество столбцов:')
# col_count = int(input())
# print('вводим матрицу:')
# A = []
# for i in range(row_count):
#     A.append(list(map(int, input().split())))
############################################################

############################################################ Задание матрицы
B = [[4, 0, 2, 2, 4, 1],
     [1, 2, 0, 2, 4, 1],
     [3, 2, 1, 2, 4, 1],
     [3, 2, 1, 2, 4, 1],
     [3, 2, 1, 2, 4, 1]]
A = B
row_count = 5
col_count = 6
############################################################

############################################################ Создаем матрицу-строку
string_matrix = ''
for i in range(row_count):
    for j in range(col_count):
        string_matrix += str(A[i][j])
############################################################ 

minm = canonicalize(row_count, col_count, string_matrix)
print('программа выводит:')
# matrix_print([row_count, col_count, A])
matrix_str_print(minm)
print('матрица-строка:', minm[2])


программа выводит:
0 1 1 2 2 4 
1 1 3 2 2 4 
1 1 3 2 2 4 
1 1 3 2 2 4 
2 1 4 0 2 4 
матрица-строка: 011224113224113224113224214024


In [26]:
a = np.array([[6, 1, 6, 1, 1],
              [1, 2, 5, 3, 0],
              [6, 3, 4, 3, 0],
              [6, 4, 3, 3, 0],
              [5, 2, 3, 1, 0],
              [6, 1, 6, 1, 2]])
rows_unordered_cols_ordered_separately = np.sort(a) # ordered columns in each row separately, but no rows
print('rows_unordered_cols_ordered_separately:\n', rows_unordered_cols_ordered_separately)
print(type(rows_unordered_cols_ordered_separately[0,0]))


str_rows_unordered_list = []
for i in range(rows_unordered_cols_ordered_separately.shape[0]):
    str_rows_unordered_list.append(''.join(str(e) for e in rows_unordered_cols_ordered_separately[i]))
print('str_rows_unordered_list', str_rows_unordered_list)

rows_order = np.argsort(str_rows_unordered_list)
rows_ordered = np.empty((0, a.shape[1]), int)

rows_ordered_cols_separately_ordered = np.empty((0, a.shape[1]), int)


for i in rows_order:
    rows_ordered = np.concatenate((rows_ordered, [a[i]]))
    rows_ordered_cols_separately_ordered = np.vstack((rows_ordered_cols_separately_ordered,
                                                           [rows_unordered_cols_ordered_separately[i]]))

print('rows_order:\n', rows_order)
print(type(rows_ordered_cols_separately_ordered[0,0]))
print('rows_ordered_cols_separately_ordered(imaging for group division):\n', rows_ordered_cols_separately_ordered)
print('------------------------------------------------------------------')
print('rows_ordered:\n', rows_ordered)
print(type(rows_ordered[0][0]))
# c = np.sort(b, axis= 0)
# print(c)

rows_unordered_cols_ordered_separately:
 [[1 1 1 6 6]
 [0 1 2 3 5]
 [0 3 3 4 6]
 [0 3 3 4 6]
 [0 1 2 3 5]
 [1 1 2 6 6]]
<class 'numpy.int64'>
str_rows_unordered_list ['11166', '01235', '03346', '03346', '01235', '11266']
rows_order:
 [1 4 2 3 0 5]
<class 'numpy.int64'>
rows_ordered_cols_separately_ordered(imaging for group division):
 [[0 1 2 3 5]
 [0 1 2 3 5]
 [0 3 3 4 6]
 [0 3 3 4 6]
 [1 1 1 6 6]
 [1 1 2 6 6]]
------------------------------------------------------------------
rows_ordered:
 [[1 2 5 3 0]
 [5 2 3 1 0]
 [6 3 4 3 0]
 [6 4 3 3 0]
 [6 1 6 1 1]
 [6 1 6 1 2]]
<class 'numpy.int64'>


In [24]:
groups_tmp = collections.Counter()
print(type(groups_tmp))
rows_group_division = []
for row_index in rows_order:
    groups_tmp[str_rows_unordered_list[row_index]] += 1
    if (groups_tmp[str_rows_unordered_list[row_index]] == 1):
        rows_group_division.append(1)
    else:
        rows_group_division[-1] += 1
print('rows_group_division:\n', rows_group_division)

<class 'collections.Counter'>
rows_group_division:
 [2, 2, 1, 1]


In [40]:
rows_ordered_separately = np.sort(rows_ordered, axis = 0) # ordered columns in each row separately, but no rows
print('rows_ordered_separately:\n', rows_ordered_separately)
str_cols_unordered_list = []
for i in range(rows_ordered_separately.shape[1]):
    str_cols_unordered_list.append(''.join(str(col) for col in rows_ordered_separately[:, i]))

print('str_cols_unordered_list: ', str_cols_unordered_list)

cols_order = np.argsort(str_cols_unordered_list)
print(cols_order)

cols_ordered = np.empty((a.shape[0], 0), int) # it will really cols_ordered_rows_ordered
cols_ordered_rows_separately_ordered = np.empty((a.shape[0], 0), int)
for i in cols_order:
    cols_ordered = np.concatenate((cols_ordered, rows_ordered[:, i:i+1]), axis=1)
    cols_ordered_rows_separately_ordered = np.concatenate((cols_ordered_rows_separately_ordered,
                                                           rows_ordered_separately[:, i:i+1]), axis=1)
print('cols_ordered_rows_separately_ordered(imaging for group division):\n', cols_ordered_rows_separately_ordered)
print('------------------------------------------------------------------')
print('cols_ordered_rows_ordered:\n', cols_ordered)

rows_ordered_separately:
 [[1 1 3 1 0]
 [5 1 3 1 0]
 [6 2 4 1 0]
 [6 2 5 3 0]
 [6 3 6 3 1]
 [6 4 6 3 2]]
str_cols_unordered_list:  ['156666', '112234', '334566', '111333', '000012']
[4 3 1 0 2]
cols_ordered_rows_separately_ordered(imaging for group division):
 [[0 1 1 1 3]
 [0 1 1 5 3]
 [0 1 2 6 4]
 [0 3 2 6 5]
 [1 3 3 6 6]
 [2 3 4 6 6]]
------------------------------------------------------------------
cols_ordered:
 [[0 3 2 1 5]
 [0 1 2 5 3]
 [0 3 3 6 4]
 [0 3 4 6 3]
 [1 1 1 6 6]
 [2 1 1 6 6]]


In [41]:
groups_tmp = collections.Counter()
print(type(groups_tmp))
cols_group_division = []
for col_index in cols_order:
    groups_tmp[str_cols_unordered_list[col_index]] += 1
    if (groups_tmp[str_cols_unordered_list[col_index]] == 1):
        cols_group_division.append(1)
    else:
        cols_group_division[-1] += 1
print('cols_group_division:\n', cols_group_division)

<class 'collections.Counter'>
cols_group_division:
 [1, 1, 1, 1, 1]


In [57]:
group_division = []
cur_row = cur_col = 0
max_group_count = max(len(cols_group_division), len(rows_group_division))
for i in range(max_group_count):
    rows_count = rows_group_division[-1]
    cols_count = cols_group_division[-1]
    if i < len(rows_group_division):
        rows_count = rows_group_division[i]
        cur_row += rows_count
    if i < len(cols_group_division):
        cols_count = cols_group_division[i]
        cur_col += cols_count
    group_division.append(((cur_row - rows_count, cur_row), (cur_col - cols_count, cur_col)))
    
    
group_sorted_matrix = cols_ordered
print('group sorted matrix:\n', group_sorted_matrix)
print('group_division: ', group_division)

group sorted matrix:
 [[0 3 2 1 5]
 [0 1 2 5 3]
 [0 3 3 6 4]
 [0 3 4 6 3]
 [1 1 1 6 6]
 [2 1 1 6 6]]
group_division:  [((0, 2), (0, 1)), ((2, 4), (1, 2)), ((4, 5), (2, 3)), ((5, 6), (3, 4)), ((5, 6), (4, 5))]


отсюда оформляем весь вышенаписанный код в одну какую-то красивую фукнцию 1ой итерации сортировки:

In [125]:
def canonization(a, is_root=1):
#     print('start_matrix:')
#     print(a)
    rows_unordered_cols_ordered_separately = np.sort(a) # ordered columns in each row separately, but no rows

    str_rows_unordered_list = []
    for i in range(rows_unordered_cols_ordered_separately.shape[0]): 
        str_rows_unordered_list.append(''.join(str(e) for e in rows_unordered_cols_ordered_separately[i]))

    rows_order = np.argsort(str_rows_unordered_list)


    rows_ordered = np.empty((0, a.shape[1]), int)
    for i in rows_order:
        rows_ordered = np.concatenate((rows_ordered, [a[i]]))


    #print('rows_ordered:\n', rows_ordered)
    # тут столбцы
    rows_ordered_separately = np.sort(rows_ordered, axis = 0) # ordered columns in each row separately, but no rows

    str_cols_unordered_list = []
    for i in range(rows_ordered_separately.shape[1]):
        str_cols_unordered_list.append(''.join(str(col) for col in rows_ordered_separately[:, i]))


    cols_order = np.argsort(str_cols_unordered_list)

    cols_ordered = np.empty((a.shape[0], 0), int) # it will really cols_ordered_rows_ordered
    for i in cols_order:
        cols_ordered = np.concatenate((cols_ordered, rows_ordered[:, i:i+1]), axis=1)

    #print('cols_ordered_rows_ordered:\n', cols_ordered)

    # тут собираем более подробную информацию про разбиение на группы

    groups_tmp = collections.Counter()
    rows_group_division = []
    for row_index in rows_order:
        groups_tmp[str_rows_unordered_list[row_index]] += 1
        if (groups_tmp[str_rows_unordered_list[row_index]] == 1):
            rows_group_division.append(1)
        else:
            rows_group_division[-1] += 1
    #print('rows_group_division:\n', rows_group_division)

    groups_tmp = collections.Counter()
    #print(type(groups_tmp))
    cols_group_division = []
    for col_index in cols_order:
        groups_tmp[str_cols_unordered_list[col_index]] += 1
        if (groups_tmp[str_cols_unordered_list[col_index]] == 1):
            cols_group_division.append(1)
        else:
            cols_group_division[-1] += 1
    #print('cols_group_division:\n', cols_group_division)

    group_division = []
    cur_row = cur_col = 0
    max_group_count = max(len(cols_group_division), len(rows_group_division))
    for i in range(max_group_count):
        rows_count = rows_group_division[-1]
        cols_count = cols_group_division[-1]
        if i < len(rows_group_division):
            rows_count = rows_group_division[i]
            cur_row += rows_count
        if i < len(cols_group_division):
            cols_count = cols_group_division[i]
            cur_col += cols_count
        group_division.append(((cur_row - rows_count, cur_row), (cur_col - cols_count, cur_col)))

    permutations = [rows_order, cols_order]
#     print('permutations: ', permutations)
    group_sorted_matrix = cols_ordered
    if is_root:
#         print(group_sorted_matrix, group_division, permutations)
        for indices in group_division:
            submatrix = group_sorted_matrix[indices[0][0]:indices[0][1],indices[1][0]:indices[1][1]]
            [tmp_submatrix, tmp_subgroup_division, group_permutation] = canonization(submatrix, 0)
#             print('group_sorted_matrix::', group_sorted_matrix)
#             print('tmp_submatrix, group_permutation',tmp_submatrix, group_permutation)

            tmp_subrows = np.copy(group_sorted_matrix[indices[0][0]:indices[0][1], :])
            tmp_subRowPemutation = np.copy(rows_order[indices[0][0]:indices[0][1]])
#             print('tmp_subRowPemutation', tmp_subRowPemutation)
#             print('tmp_subrows',tmp_subrows)
#             print('len(tmp_subrows)=', len(tmp_subrows))
            for row_index in range(len(tmp_subrows)):
#                 print('tmp_subrows[group_permutation[0][row_index]]:', 'group_permutation[0][row_index]=', group_permutation[0][row_index], tmp_subrows[group_permutation[0][row_index]])
                group_sorted_matrix[indices[0][0] + row_index] = tmp_subrows[group_permutation[0][row_index]]
                rows_order[indices[0][0] + row_index] = tmp_subRowPemutation[group_permutation[0][row_index]]
        
            tmp_subcols = np.copy(group_sorted_matrix[:, indices[1][0]:indices[1][1]])
            
            tmp_subColPemutation = np.copy(cols_order[indices[1][0]:indices[1][1]])
#             print('tmp_subcols', tmp_subcols)
#             print('теперь колы group_sorted_matrix', group_sorted_matrix)
            for col_index in range(tmp_subcols.shape[1]):
                group_sorted_matrix[:, indices[1][0] + col_index:indices[1][0] + col_index + 1] = tmp_subcols[:, group_permutation[1][col_index]:group_permutation[1][col_index]+1]
                cols_order[indices[1][0] + col_index] = tmp_subColPemutation[group_permutation[1][col_index]]
#                 print(group_sorted_matrix)

    return [group_sorted_matrix, group_division, permutations]

b = np.array([[4,4,1,2],
              [0,1,2,1],
              [4,4,0,1],
              [1,2,1,0]])
# print(b)

# dd = canonization(b)
# print(dd)

# с = np.array([[0,1,2,1,2,1],
#               [1,1,2,1,0,2],
#               [1,0,1,1,2,2],
#               [3,3,0,1,2,2]])
# print(c)
# can_c = canonization(c)
# print(can_c[0], can_c[1], can_c[2], can_c[3])
a = np.array([[6, 4, 6, 1, 1],
              [1, 2, 5, 1, 1],
              [6, 3, 4, 2, 0],
              [6, 4, 3, 2, 0],
              [5, 2, 3, 1, 0],
              [6, 1, 6, 0, 2],
              [6, 2, 6, 0, 1],
              [6, 1, 5, 0, 5]])

can_a = canonization(a)
print(can_a[0], can_a[1], can_a[2])

[[1 0 2 5 3]
 [0 1 2 6 6]
 [0 2 1 6 6]
 [0 5 1 6 5]
 [2 0 3 6 4]
 [2 0 4 6 3]
 [1 1 2 1 5]
 [1 1 4 6 6]] [((0, 1), (0, 1)), ((1, 3), (1, 2)), ((3, 4), (2, 3)), ((4, 6), (3, 4)), ((6, 7), (4, 5)), ((7, 8), (4, 5))] [array([4, 6, 5, 7, 2, 3, 1, 0]), array([3, 4, 1, 0, 2])]


012121
112102
101122
330122






In [127]:
def canonization(a, is_root=1):
    rows_unordered_cols_ordered_separately = np.sort(a) # ordered columns in each row separately, but no rows

    str_rows_unordered_list = []
    for i in range(rows_unordered_cols_ordered_separately.shape[0]): 
        str_rows_unordered_list.append(''.join(str(e) for e in rows_unordered_cols_ordered_separately[i]))

    rows_order = np.argsort(str_rows_unordered_list)
    rows_ordered = np.empty((0, a.shape[1]), int)
    for i in rows_order:
        rows_ordered = np.concatenate((rows_ordered, [a[i]]))

    # тут столбцы
    rows_ordered_separately = np.sort(rows_ordered, axis = 0) # ordered columns in each row separately, but no rows

    str_cols_unordered_list = []
    for i in range(rows_ordered_separately.shape[1]):
        str_cols_unordered_list.append(''.join(str(col) for col in rows_ordered_separately[:, i]))


    cols_order = np.argsort(str_cols_unordered_list)

    cols_ordered = np.empty((a.shape[0], 0), int) # it will really cols_ordered_rows_ordered
    for i in cols_order:
        cols_ordered = np.concatenate((cols_ordered, rows_ordered[:, i:i+1]), axis=1)



    # тут собираем более подробную информацию про разбиение на группы

    groups_tmp = collections.Counter()
    rows_group_division = []
    for row_index in rows_order:
        groups_tmp[str_rows_unordered_list[row_index]] += 1
        if (groups_tmp[str_rows_unordered_list[row_index]] == 1):
            rows_group_division.append(1)
        else:
            rows_group_division[-1] += 1

    groups_tmp = collections.Counter()

    cols_group_division = []
    for col_index in cols_order:
        groups_tmp[str_cols_unordered_list[col_index]] += 1
        if (groups_tmp[str_cols_unordered_list[col_index]] == 1):
            cols_group_division.append(1)
        else:
            cols_group_division[-1] += 1


    group_division = []
    cur_row = cur_col = 0
    max_group_count = max(len(cols_group_division), len(rows_group_division))
    for i in range(max_group_count):
        rows_count = rows_group_division[-1]
        cols_count = cols_group_division[-1]
        if i < len(rows_group_division):
            rows_count = rows_group_division[i]
            cur_row += rows_count
        if i < len(cols_group_division):
            cols_count = cols_group_division[i]
            cur_col += cols_count
        group_division.append(((cur_row - rows_count, cur_row), (cur_col - cols_count, cur_col)))

    permutations = [rows_order, cols_order]

    group_sorted_matrix = cols_ordered
    if is_root:

        for indices in group_division:
            submatrix = group_sorted_matrix[indices[0][0]:indices[0][1],indices[1][0]:indices[1][1]]
            [tmp_submatrix, tmp_subgroup_division, group_permutation] = canonization(submatrix, 0)

            tmp_subrows = np.copy(group_sorted_matrix[indices[0][0]:indices[0][1], :])
            tmp_subRowPemutation = np.copy(rows_order[indices[0][0]:indices[0][1]])

            for row_index in range(len(tmp_subrows)):
                group_sorted_matrix[indices[0][0] + row_index] = tmp_subrows[group_permutation[0][row_index]]
                rows_order[indices[0][0] + row_index] = tmp_subRowPemutation[group_permutation[0][row_index]]
        
            tmp_subcols = np.copy(group_sorted_matrix[:, indices[1][0]:indices[1][1]])
            
            tmp_subColPemutation = np.copy(cols_order[indices[1][0]:indices[1][1]])

            for col_index in range(tmp_subcols.shape[1]):
                group_sorted_matrix[:, indices[1][0] + col_index:indices[1][0] + col_index + 1] = tmp_subcols[:, group_permutation[1][col_index]:group_permutation[1][col_index]+1]
                cols_order[indices[1][0] + col_index] = tmp_subColPemutation[group_permutation[1][col_index]]

    return [group_sorted_matrix, group_division, permutations]